id: environment-sensor-for-jetson-nano
ref: waveshare/environment-sensor-for-jetson-nano
vendor: waveshare
sku: environment-sensor-for-jetson-nano
name: Environment Sensor for Jetson Nano
description: Environment Sensors Module for Jetson Nano, I2C Bus, with 1.3inch OLED
  Display
status: ''
extra: {}
links:
  products:
  - https://www.waveshare.com/product/environment-sensor-for-jetson-nano.htm
  images:
  - https://www.waveshare.com/media/catalog/product/cache/1/small_image/171x171/9df78eab33525d08d6e5fb8d27136e95/e/n/environment-sensor-for-jetson-nano-1_4.jpg
