id: product3
ref: enocean/product3
vendor: enocean
sku: product3
name: Product3
description: Description of Product 3
status: Discontinued
extra:
  attribute1: value1
links:
  products:
  - https://www.enocean.com/en/products/product3
  images:
  - https://www.enocean.com/en/products/images/product3.jpg
