id: product2
ref: enocean/product2
vendor: enocean
sku: product2
name: Product2
description: Description of Product 2
status: ''
extra: {}
links:
  products:
  - https://www.enocean.com/en/products/product2
  images: []
