id: product1
ref: enocean/product1
vendor: enocean
sku: product1
name: Product1
description: Description of Product 1
status: Available
extra:
  attribute1: value1
  attribute2: value2
links:
  products:
  - https://www.enocean.com/en/products/product1
  images:
  - https://www.enocean.com/en/products/images/product1.jpg
