alternatives: []
certifications: []
description: Description of Product 2
extra: {}
links:
  datasheets: []
  examples: []
  images: []
  models: []
  products:
  - https://www.enocean.com/en/products/product2
  repositories: []
name: Product2
ref: enocean/product2
release_date: null
sku: product2
spec: null
status: ''
vendor: enocean
